[package]
name = "danxe"
version = "0.1.0"
edition = "2021"

[lib]
name = "danxe"
crate-type = ["lib"]

[[bin]]
name = "danxe"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
itertools = "0.10.5"
